# Generated by Django 4.1.2 on 2022-10-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bormusov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bormusov.manufacturer', verbose_name='Имя продовца'),
        ),
    ]
